In [ ]:
import pandas as pd

In [ ]:
lst=[1,2,3,4,56,7];
sr1=pd.Series(lst);
sr1

0     1
1     2
2     3
3     4
4    56
5     7
dtype: int64

In [4]:
dict1={
    'name':["aryan","leo","rolex","allu"],
    "age":[20,69,45,50],
    "state":["uk","tamil-nadu","telangna","kerla"]
};
df=pd.DataFrame(dict1);
df

    name  age       state
0  aryan   20          uk
1    leo   69  tamil-nadu
2  rolex   45    telangna
3   allu   50       kerla

In [10]:
print(df.head(2))
print(df.tail(7))

    name  age       state
0  aryan   20          uk
1    leo   69  tamil-nadu
    name  age       state
0  aryan   20          uk
1    leo   69  tamil-nadu
2  rolex   45    telangna
3   allu   50       kerla

In [11]:
df

    name  age       state
0  aryan   20          uk
1    leo   69  tamil-nadu
2  rolex   45    telangna
3   allu   50       kerla

In [25]:
# df.loc[0][0]
df.loc[1]

name            leo
age              69
state    tamil-nadu
Name: 1, dtype: object