In [60]:
import pandas as pd;
import numpy as np;
from sklearn.preprocessing import OneHotEncoder;
encoder=OneHotEncoder();

In [61]:
df=pd.read_excel("flight_price.xlsx");
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [62]:
df.head(2)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662

In [63]:
df["date"]=df["Date_of_Journey"].str.split("/").str[0];
df["date"]=df["date"].astype(int);
df["month"]=df["Date_of_Journey"].str.split("/").str[1];
df["month"]=df["date"].astype(int);
df["year"]=df["Date_of_Journey"].str.split("/").str[2];
df["year"]=df["date"].astype(int);

In [64]:
df.drop("Date_of_Journey",axis=1,inplace=True)
df.drop("Route",axis=1,inplace=True)

In [65]:
df.head(3)

,Airline,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,date,month,year
0,IndiGo,Banglore,New Delhi,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,24,24
1,Air India,Kolkata,Banglore,05:50,13:15,7h 25m,2 stops,No info,7662,1,1,1
2,Jet Airways,Delhi,Cochin,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,9,9

In [66]:
df["Dep_Hour"]=df["Dep_Time"].str.split(":").str[0]
df["Dep_Min"]=df["Dep_Time"].str.split(":").str[1]

In [67]:
df.drop("Dep_Time",axis=1,inplace=True)

In [68]:
df["Dep_Hour"]=df["Dep_Hour"].astype(int)
df["Dep_Min"]=df["Dep_Min"].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Arrival_Time     10683 non-null  object
 4   Duration         10683 non-null  object
 5   Total_Stops      10682 non-null  object
 6   Additional_Info  10683 non-null  object
 7   Price            10683 non-null  int64
 8   date             10683 non-null  int64
 9   month            10683 non-null  int64
 10  year             10683 non-null  int64
 11  Dep_Hour         10683 non-null  int64
 12  Dep_Min          10683 non-null  int64
dtypes: int64(6), object(7)
memory usage: 1.1+ MB

In [69]:
df.head()

,Airline,Source,Destination,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,date,month,year,Dep_Hour,Dep_Min
0,IndiGo,Banglore,New Delhi,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,24,24,22,20
1,Air India,Kolkata,Banglore,13:15,7h 25m,2 stops,No info,7662,1,1,1,5,50
2,Jet Airways,Delhi,Cochin,04:25 10 Jun,19h,2 stops,No info,13882,9,9,9,9,25
3,IndiGo,Kolkata,Banglore,23:30,5h 25m,1 stop,No info,6218,12,12,12,18,5
4,IndiGo,Banglore,New Delhi,21:35,4h 45m,1 stop,No info,13302,1,1,1,16,50

In [70]:
df["Arrival_Time"]=df["Arrival_Time"].str.split(" ").str[0]

In [71]:
df["Arrival_Hour"]=df["Arrival_Time"].str.split(":").str[0]
df["Arrival_Min"]=df["Arrival_Time"].str.split(":").str[1]

In [ ]:
df.drop("Arrival_Time",axis=1,inplace=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Duration         10683 non-null  object
 4   Total_Stops      10682 non-null  object
 5   Additional_Info  10683 non-null  object
 6   Price            10683 non-null  int64
 7   date             10683 non-null  int64
 8   month            10683 non-null  int64
 9   year             10683 non-null  int64
 10  Dep_Hour         10683 non-null  int64
 11  Dep_Min          10683 non-null  int64
 12  Arrival_Hour     10683 non-null  object
 13  Arrival_Min      10683 non-null  object
dtypes: int64(6), object(8)
memory usage: 1.1+ MB

In [75]:
df["Arrival_Hour"]=df["Arrival_Hour"].astype(int)
df["Arrival_Min"]=df["Arrival_Min"].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Duration         10683 non-null  object
 4   Total_Stops      10682 non-null  object
 5   Additional_Info  10683 non-null  object
 6   Price            10683 non-null  int64
 7   date             10683 non-null  int64
 8   month            10683 non-null  int64
 9   year             10683 non-null  int64
 10  Dep_Hour         10683 non-null  int64
 11  Dep_Min          10683 non-null  int64
 12  Arrival_Hour     10683 non-null  int64
 13  Arrival_Min      10683 non-null  int64
dtypes: int64(8), object(6)
memory usage: 1.1+ MB

In [76]:
df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,date,month,year,Dep_Hour,Dep_Min,Arrival_Hour,Arrival_Min
0,IndiGo,Banglore,New Delhi,2h 50m,non-stop,No info,3897,24,24,24,22,20,1,10
1,Air India,Kolkata,Banglore,7h 25m,2 stops,No info,7662,1,1,1,5,50,13,15
2,Jet Airways,Delhi,Cochin,19h,2 stops,No info,13882,9,9,9,9,25,4,25
3,IndiGo,Kolkata,Banglore,5h 25m,1 stop,No info,6218,12,12,12,18,5,23,30
4,IndiGo,Banglore,New Delhi,4h 45m,1 stop,No info,13302,1,1,1,16,50,21,35

In [85]:
df["Total_Stops"].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [94]:
df["Total_Stops"].mode()

0    1 stop
Name: Total_Stops, dtype: object

In [95]:
df["Total_Stops"]=df["Total_Stops"].map({'non-stop':0, '2 stops':2, '1 stop':1, '3 stops':3,np.nan:1, '4 stops':4})

In [99]:
df["Total_Stops"].unique()
df.head(2)

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,date,month,year,Dep_Hour,Dep_Min,Arrival_Hour,Arrival_Min
0,IndiGo,Banglore,New Delhi,2h 50m,0,No info,3897,24,24,24,22,20,1,10
1,Air India,Kolkata,Banglore,7h 25m,2,No info,7662,1,1,1,5,50,13,15

In [140]:
df["Duration_Hours"] = df["Duration"].str.extract(r"(\d+)h", expand=False).fillna(0).astype(int)
df["Duration_Min"] = df["Duration"].str.extract(r"(\d+)m", expand=False).fillna(0).astype(int)

In [141]:
df.head(1)

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,date,month,year,Dep_Hour,Dep_Min,Arrival_Hour,Arrival_Min,Duration_Hours,Duration_Min
0,IndiGo,Banglore,New Delhi,2h 50m,0,No info,3897,24,24,24,22,20,1,10,2,50

In [142]:
df.drop("Duration",axis=1,inplace=True)

In [143]:
df.head(1)

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,date,month,year,Dep_Hour,Dep_Min,Arrival_Hour,Arrival_Min,Duration_Hours,Duration_Min
0,IndiGo,Banglore,New Delhi,0,No info,3897,24,24,24,22,20,1,10,2,50

In [157]:
arr=encoder.fit_transform(df[["Airline","Source","Destination"]]).toarray();
df1=pd.DataFrame(arr,columns=encoder.get_feature_names_out());

In [158]:
df.head(1)

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,date,month,year,Dep_Hour,Dep_Min,Arrival_Hour,Arrival_Min,Duration_Hours,Duration_Min
0,IndiGo,Banglore,New Delhi,0,No info,3897,24,24,24,22,20,1,10,2,50

In [159]:
df.drop("Airline",axis=1,inplace=True)
df.drop("Source",axis=1,inplace=True)
df.drop("Destination",axis=1,inplace=True)

In [167]:
df0=pd.concat([df1,df],axis=1);

In [168]:
df0

,Airline_Air Asia,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,Airline_Multiple carriers,Airline_Multiple carriers Premium economy,Airline_SpiceJet,Airline_Trujet,...,Price,date,month,year,Dep_Hour,Dep_Min,Arrival_Hour,Arrival_Min,Duration_Hours,Duration_Min
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3897,24,24,24,22,20,1,10,2,50
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7662,1,1,1,5,50,13,15,7,25
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,13882,9,9,9,9,25,4,25,19,0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6218,12,12,12,18,5,23,30,5,25
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,13302,1,1,1,16,50,21,35,4,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4107,9,9,9,19,55,22,25,2,30
10679,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4145,27,27,27,20,45,23,20,2,35
10680,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,7229,27,27,27,8,20,11,20,3,0
10681,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,12648,1,1,1,11,30,14,10,2,40
10682,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,11753,9,9,9,10,55,19,15,8,20